


spring:
  datasource:
    url: jdbc:mysql://localhost:3305/QLStoreJelly?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    spring:
      mvc:
        cors:
          allowed-origins: "http://localhost:4200"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
      #      ddl-auto: none # Chỉ định cách Hibernate quản lý cấu trúc cơ sở dữ liệu
      # cấu hình hibernate sẽ thực hiện theo việc đặt tên csdl trên quy tắc vật lý
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      format_sql: true
    show-sql: true # Hiển thị các truy vấn SQL trong logs